export const productMock = {
  id: 'MLA1131359154',
  title: 'Libro Consultas:power Query El Recurso Máximo Excel 365 2021',
  condition: 'new',
  thumbnail_id: '656499-MLA49612018636_042022',
  catalog_product_id: null,
  listing_type_id: 'gold_special',
  permalink:
    'https://articulo.mercadolibre.com.ar/MLA-1131359154-libro-consultaspower-query-el-recurso-maximo-excel-365-2021-_JM',
  buying_mode: 'buy_it_now',
  site_id: 'MLA',
  category_id: 'MLA412445',
  domain_id: 'MLA-BOOKS',
  thumbnail: 'http://http2.mlstatic.com/D_656499-MLA49612018636_042022-I.jpg',
  currency_id: 'ARS',
  order_backend: 1,
  price: 6368,
  original_price: null,
  sale_price: null,
  sold_quantity: 5,
  available_quantity: 1,
  official_store_id: 680,
  official_store_name: 'Alfaomega',
  use_thumbnail_id: true,
  accepts_mercadopago: true,
  tags: ['good_quality_picture', 'immediate_payment', 'cart_eligible', 'shipping_guaranteed'],
  shipping: {
    store_pick_up: false,
    free_shipping: false,
    logistic_type: 'fulfillment',
    mode: 'me2',
    tags: ['fulfillment'],
    promise: null,
  },
  stop_time: '2042-04-03T04:00:00.000Z',
  seller: {
    id: 161560823,
    nickname: 'ALFAOMEGA EDITOR',
    car_dealer: false,
    real_estate_agency: false,
    _: false,
    registration_date: '2014-06-27T16:22:09.000-04:00',
    tags: ['brand', 'large_seller', 'eshop', 'mshops', 'credits_profile', 'messages_as_seller'],
    car_dealer_logo: '',
    permalink: 'http://perfil.mercadolibre.com.ar/ALFAOMEGA+EDITOR',
    seller_reputation: {
      level_id: '5_green',
      power_seller_status: 'platinum',
      transactions: {
        canceled: 283,
        completed: 8119,
        period: 'historic',
        ratings: {
          negative: 0.02,
          neutral: 0.01,
          positive: 0.97,
        },
        total: 8402,
      },
      metrics: {
        sales: {
          period: '60 days',
          completed: 1863,
        },
        claims: {
          period: '60 days',
          rate: 0.0041,
          value: 8,
        },
        delayed_handling_time: {
          period: '60 days',
          rate: 0.011,
          value: 20,
        },
        cancellations: {
          period: '60 days',
          rate: 0.001,
          value: 2,
        },
      },
    },
    eshop: {
      eshop_id: 263939,
      seller: 161560823,
      nick_name: 'ALFAOMEGA EDITOR',
      eshop_status_id: 1,
      site_id: 'MLA',
      eshop_experience: 0,
      eshop_rubro: null,
      eshop_locations: [],
      eshop_logo_url: 'http://http2.mlstatic.com/eshops-logo/161560823vacc4cb.png',
    },
  },
  seller_address: {
    comment: '',
    address_line: '',
    zip_code: '',
    id: null,
    latitude: null,
    longitude: null,
    country: {
      id: 'AR',
      name: 'Argentina',
    },
    state: {
      id: 'AR-C',
      name: 'Capital Federal',
    },
    city: {
      id: null,
      name: 'TRIBUNALES',
    },
  },
  address: {
    state_id: 'AR-C',
    state_name: 'Capital Federal',
    city_id: null,
    city_name: 'TRIBUNALES',
  },
  attributes: [
    {
      id: 'ITEM_CONDITION',
      name: 'Condición del ítem',
      value_id: '2230284',
      value_name: 'Nuevo',
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
      value_struct: null,
      values: [
        {
          id: '2230284',
          name: 'Nuevo',
          struct: null,
          source: 6808261514773724,
        },
      ],
      source: 6808261514773724,
      value_type: 'list',
    },
    {
      id: 'PACKAGE_LENGTH',
      name: 'Largo del paquete',
      value_id: null,
      value_name: '22.6 cm',
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
      value_struct: {
        number: 22.6,
        unit: 'cm',
      },
      values: [
        {
          id: null,
          name: '22.6 cm',
          struct: {
            number: 22.6,
            unit: 'cm',
          },
          source: 4333789534002961,
        },
      ],
      source: 4333789534002961,
      value_type: 'number_unit',
    },
    {
      id: 'PACKAGE_WEIGHT',
      name: 'Peso del paquete',
      value_id: null,
      value_name: '360 g',
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
      value_struct: {
        number: 360,
        unit: 'g',
      },
      values: [
        {
          id: null,
          name: '360 g',
          struct: {
            number: 360,
            unit: 'g',
          },
          source: 4333789534002961,
        },
      ],
      source: 4333789534002961,
      value_type: 'number_unit',
    },
    {
      id: 'WEIGHT',
      name: 'Peso',
      value_id: '-1',
      value_name: null,
      attribute_group_id: 'OTHERS',
      attribute_group_name: 'Otros',
      value_struct: null,
      values: [
        {
          id: '-1',
          name: null,
          struct: null,
          source: 6808261514773724,
        },
      ],
      source: 6808261514773724,
      value_type: 'number_unit',
    },
  ],
  installments: {
    quantity: 24,
    amount: 795.23,
    rate: 199.71,
    currency_id: 'ARS',
  },
  winner_item_id: null,
  discounts: null,
  promotions: [],
  inventory_id: 'QRTZ01150',
};
